In [11]:
import numpy as np 
import pandas as pd
import os

In [10]:
path_to_csv = '/home/paul/Downloads/econet_ped/echonetpediatric/pediatric_echo_avi/pediatric_echo_avi/A4C/FileList.csv'
path_train = '/home/paul/Downloads/echonet_ped_preprocessed/TRAIN'
path_val = '/home/paul/Downloads/echonet_ped_preprocessed/VAL'
path_test = '/home/paul/Downloads/echonet_ped_preprocessed/TEST'

In [3]:
df = pd.read_csv(path_to_csv)
df.head()

                         FileName     EF Sex  Age  Weight  Height  Split
0  CR32a7555-CR32a7582-000039.avi  40.83   F    0    10.2    68.5      5
1  CR32a7555-CR32a97af-000033.avi  52.62   F    1    15.5    85.0      5
2  CR32a7555-CR32a97e1-000024.avi  24.85   F    0     4.0    56.0      5
3  CR32a7555-CR32a9850-000040.avi  50.96   F    4    18.0    99.0      5
4  CR32a7555-CR32a988d-000034.avi  56.76   F    0    13.2    75.0      5

In [14]:
def get_filenames_from_dir(path):
    return {
        f[:-3] + '.avi' for f in os.listdir(path)
        if os.path.isfile(os.path.join(path, f))
    }

train_files = get_filenames_from_dir(path_train)
val_files   = get_filenames_from_dir(path_val)
test_files  = get_filenames_from_dir(path_test)

In [15]:
train_files

{'CR32a95e8-CR32a97bd-000056.avi',
 'CR3dcac35-CR3dcb675-000032.avi',
 'CR3dca698-CR3dcb47e-000047.avi',
 'CR32a95f4-CR3dcb2e5-000081.avi',
 'CR32a971a-CR3dcb43a-000047.avi',
 'CR3dca83a-CR3dcb40e-000041.avi',
 'CR3dcb8f8-CR3dcb9ab-000045.avi',
 'CR3dcabe1-CR3dcadd2-000039.avi',
 'CR3dca81d-CR3dcb677-000033.avi',
 'CR3dcac2a-CR3dcb800-000029.avi',
 'CR4884eb4-CR4884f52-000063.avi',
 'CR32a970c-CR4884f3d-000032.avi',
 'CR3dcb078-CR3dcb1bd-000044.avi',
 'CR3dcab7b-CR3dcb68d-000073.avi',
 'CR3dcabbb-CR3dcad6e-000034.avi',
 'CR3dca7c4-CR3dcb47f-000068.avi',
 'CR32a9670-CR32a99cd-000052.avi',
 'CR3dca72f-CR3dcae98-000046.avi',
 'CR3dcb145-CR3dcb3ae-000048.avi',
 'CR32a756d-CR32a759b-000094.avi',
 'CR32a756a-CR32a97b7-000066.avi',
 'CR3dca836-CR3dcab14-000003.avi',
 'CR32a973a-CR3dcb843-000072.avi',
 'CR32a95e8-CR32a9abd-000060.avi',
 'CR3dca6af-CR3dcaa8d-000035.avi',
 'CR32a9747-CR3dcb99c-000045.avi',
 'CR3dcab94-CR3dcaf20-000028.avi',
 'CR3dcabdb-CR3dcb373-000046.avi',
 'CR3dcb156-CR3dcb3dd-000090.avi',
 'CR32a95e9-CR3dcaadd-000029.avi',
 'CR32a9704-CR32a99ed-000002.avi',
 'CR3dca712-CR3dcb6dc-000032.avi',
 'CR3dcb151-CR3dcb75a-000066.avi',
 'CR3dca82d-CR3dcb2c2-000055.avi',
 'CR3dcb106-CR3dcb2ee-000048.avi',
 'CR3dcab8e-CR3dcad02-000046.avi',
 'CR32a970d-CR32a99fa-000071.avi',
 'CR3dcb54a-CR3dcb774-000071.avi',
 'CR32a961e-CR32a9882-000035.avi',
 'CR32a964d-CR4884f3e-000075.avi',
 'CR32a9652-CR32a9861-000068.avi',
 'CR3dcb181-CR3dcb460-000044.avi',
 'CR32a95dd-CR32a9a67-000041.avi',
 'CR3dcb126-CR3dcb7fa-000067.avi',
 'CR32a7556-CR3dcacc6-000081.avi',
 'CR3dca6bb-CR3dca8a5-000064.avi',
 'CR3dca690-CR3dca9a5-000023.avi',
 'CR3dcb08c-CR3dcb97b-000062.avi',
 'CR3dca813-CR3dcb656-000035.avi',
 'CR3dca7b7-CR3dcaa37-000077.avi',
 'CR3dca755-CR3dcadfe-000054.avi',
 'CR32a963a-CR3dcae4a-000065.avi',
 'CR32a7570-CR32a759e-000054.avi',
 'CR3dca705-CR3dca911-000048.avi',
 'CR32a964f-CR32a9ae7-000052.avi',
 'CR3dcb078-CR3dcb715-000035.avi',
 'CR32a95c5-CR3dcb207-000049.avi',
 'CR3dcb58e-CR3dcb85a-000052.avi',
 'CR32a9690-CR3dca9d3-000045.avi',
 'CR3dca75f-CR3dca9a7-000039.avi',
 'CR3dca776-CR3dca9d4-000053.avi',
 'CR3dca712-CR3dcb4b1-000051.avi',
 'CR3dcb5a6-CR3dcb89a-000061.avi',
 'CR32a966c-CR3dcb1a9-000053.avi',
 'CR32a9662-CR3dcb1e7-000031.avi',
 'CR32a756f-CR32a9a8e-000047.avi',
 'CR32a7559-CR32a7586-000045.avi',
 'CR3dcb076-CR3dcb7cd-000062.avi',
 'CR32a9708-CR3dcb685-000003.avi',
 'CR3dca709-CR3dcaf0a-000052.avi',
 'CR3dca7f7-CR3dcb3c8-000102.avi',
 'CR32a963b-CR32a9837-000068.avi',
 'CR3dca72c-CR3dca94c-000051.avi',
 'CR32a95f7-CR3dcb48c-000021.avi',
 'CR3dca748-CR3dcad76-000039.avi',
 'CR32a96cd-CR32a9969-000060.avi',
 'CR32a9670-CR4884f09-000046.avi',
 'CR3dcb541-CR3dcb757-000041.avi',
 'CR3dca844-CR3dcab2f-000079.avi',
 'CR3dca7ec-CR3dcaa92-000061.avi',
 'CR32a96d8-CR32a9984-000020.avi',
 'CR32a968e-CR3dcb6ee-000070.avi',
 'CR3dca823-CR3dcb7e5-000065.avi',
 'CR32a969b-CR32a9904-000068.avi',
 'CR3dca797-CR3dcaa03-000029.avi',
 'CR3dcab8d-CR3dcad01-000038.avi',
 'CR3dcb0ad-CR3dcb229-000061.avi',
 'CR3dca705-CR3dcacae-000034.avi',
 'CR3dcab9f-CR3dcad26-000067.avi',
 'CR32a95c5-CR32a9844-000049.avi',
 'CR32a9760-CR3dcb1c7-000036.avi',
 'CR3dcb4d4-CR3dcb607-000067.avi',
 'CR3dca823-CR3dcb2fa-000048.avi',
 'CR3dca755-CR3dcb832-000041.avi',
 'CR3dcab5a-CR3dcb7ed-000041.avi',
 'CR32a7562-CR32a9acf-000068.avi',
 'CR32a96a3-CR3dcb68e-000036.avi',
 'CR3dcaf9a-CR3dcaff3-000028.avi',
 'CR3dcb193-CR3dcb4a0-000084.avi',
 'CR3dcb5a1-CR3dcb887-000028.avi',
 'CR32a95ed-CR32a97b5-000044.avi',
 'CR3dcabda-CR3dcb1ea-000058.avi',
 'CR3dca6f4-CR3dca91a-000034.avi',
 'CR3dca84d-CR3dcae5c-000053.avi',
 'CR3dcb4c5-CR3dcb5e7-000051.avi',
 'CR3dcaf93-CR3dcafd5-000037.avi',
 'CR3dca703-CR3dca90e-000064.avi',
 'CR3dca7f5-CR3dcb318-000043.avi',
 'CR32a961e-CR3dcb297-000040.avi',
 'CR3dca82e-CR3dcab06-000041.avi',
 'CR3dcb4ee-CR3dcb64c-000032.avi',
 'CR32a9763-CR3dca923-000029.avi',
 'CR32a964c-CR32a9851-000037.avi',
 'CR3dcabb4-CR3dcaf2d-000024.avi',
 'CR32a95e4-CR3dcb735-000041.avi',
 'CR3dcb080-CR3dcb996-000039.avi',
 'CR32a96b3-CR32a9a45-000058.avi',
 'CR3dca6f1-CR4884f00-000043.avi',
 'CR32a9682-CR32a98d0-000066.avi',
 'CR3dcb0cd-CR3dcb68f-000066.avi',
 'CR32a96f8-CR32a99d5-000047.avi',
 'CR3dcb143-CR3dcb3aa-000053.avi',
 'CR3dca72f-CR3dca951-000042.avi',
 'CR3dcb8e5-CR3dcb959-000057.avi',
 'CR3dcac4f-CR3dcaec8-000052.avi',
 'CR32a95c2-CR32a977e-000048.avi',
 'CR3dca722-CR3dca941-000042.avi',
 'CR3dcb58d-CR3dcb857-000046.avi',
 'CR3dcac1e-CR3dcb6f6-000075.avi',
 'CR32a96ea-CR3dcb464-000032.avi',
 'CR3dcab90-CR3dcad06-000038.avi',
 'CR32a7571-CR32a99ba-000056.avi',
 'CR3dcb0b4-CR3dcb234-000098.avi',
 'CR32a9711-CR32a9a00-000032.avi',
 'CR3dca834-CR3dcb865-000034.avi',
 'CR3dca6a5-CR3dca889-000093.avi',
 'CR32a961d-CR3dca8cc-000113.avi',
 'CR3dca694-CR3dca872-000061.avi',
 'CR3dcb09a-CR3dcb20a-000042.avi',
 'CR3dca683-CR3dcad45-000044.avi',
 'CR3dcb558-CR3dcb7ae-000055.avi',
 'CR3dca73e-CR3dcafd1-000028.avi',
 'CR3dca6f1-CR3dcadc5-000042.avi',
 'CR32a95c8-CR32a9784-000042.avi',
 'CR3dcb08c-CR3dcb1e2-000028.avi',
 'CR3dcb4f3-CR3dcb658-000029.avi',
 'CR3dcb0ef-CR3dcb2bb-000032.avi',
 'CR32a96fb-CR32a99dd-000047.avi',
 'CR3dca806-CR3dcaabe-000052.avi',
 'CR3dcabc6-CR3dcafdd-000090.avi',
 'CR3dca724-CR3dca944-000070.avi',
 'CR32a969a-CR32a9903-000046.avi',
 'CR32a95ee-CR32a9939-000036.avi',
 'CR32a9772-CR3dcb462-000014.avi',
 'CR3dcabb8-CR3dcad8f-000054.avi',
 'CR32a95f7-CR32a980f-000077.avi',
 'CR32a95bb-CR3dcb79e-000039.avi',
 'CR3dca7d1-CR3dcaa5e-000057.avi',
 'CR3dca7da-CR3dcad23-000044.avi',
 'CR3dca70b-CR3dca91c-000030.avi',
 'CR32a9706-CR3dcb97f-000053.avi',
 'CR3dcb11f-CR3dcb349-000052.avi',
 'CR32a95c3-CR3dcb8bb-000067.avi',
 'CR3dcb513-CR3dcb6b7-000087.avi',
 'CR3dca79b-CR3dcaa09-000042.avi',
 'CR3dca72a-CR3dcaa25-000038.avi',
 'CR3dcb533-CR3dcb733-000052.avi',
 'CR3dca7e3-CR3dcb7df-000030.avi',
 'CR3dcb4d5-CR3dcb932-000079.avi',
 'CR32a96aa-CR3dcaa71-000038.avi',
 'CR32a95f1-CR32a9ada-000065.avi',
 'CR4884ea2-CR4884ee7-000063.avi',
 'CR3dca7ab-CR3dcaa23-000063.avi',
 'CR3dcabd0-CR3dcad9b-000055.avi',
 'CR3dca6ef-CR3dca8f2-000052.avi',
 'CR32a96ef-CR32a99bf-000110.avi',
 'CR3dca6ab-CR3dcaeed-000043.avi',
 'CR3dcac72-CR4884f2c-000035.avi',
 'CR32a9711-CR4884ed4-000059.avi',
 'CR32a9769-CR4884f14-000058.avi',
 'CR3dcac3f-CR3dcaea9-000034.avi',
 'CR32a9689-CR3dcb236-000028.avi',
 'CR3dcb510-CR3dcb6b0-000063.avi',
 'CR3dca72d-CR3dcb716-000051.avi',
 'CR3dcb501-CR3dcb680-000073.avi',
 'CR3dcb0df-CR3dcb68c-000047.avi',
 'CR32a9730-CR32a9a5e-000037.avi',
 'CR3dcb08a-CR3dcb3e7-000063.avi',
 'CR3dca703-CR3dcadae-000068.avi',
 'CR3dca703-CR3dcaa85-000037.avi',
 'CR3dcb4bd-CR3dcb5c5-000033.avi',
 'CR32a95f5-CR3dcb81b-000049.avi',
 'CR3dca731-CR3dca954-000048.avi',
 'CR3dcb172-CR3dcb831-000046.avi',
 'CR3dca83e-CR3dcab27-000079.avi',
 'CR32a976e-CR3dcb6ec-000033.avi',
 'CR3dca799-CR3dcb613-000059.avi',
 'CR3dcb0ec-CR3dcb895-000047.avi',
 'CR3dca6b5-CR3dca8cd-000040.avi',
 'CR3dcb527-CR3dcb6fb-000058.avi',
 'CR3dcb096-CR3dcb1fc-000048.avi',
 'CR3dca6f9-CR3dcb3bc-000048.avi',
 'CR3dcabff-CR3dcae13-000048.avi',
 'CR32a963d-CR3dcae14-000051.avi',
 'CR3dcb159-CR3dcb3e5-000049.avi',
 'CR3dca77c-CR3dca9dd-000070.avi',
 'CR32a95f7-CR3dcb684-000029.avi',
 'CR32a95d7-CR32a9794-000046.avi',
 'CR3dcb594-CR3dcb863-000064.avi',
 'CR3dcac76-CR3dcb3f3-000036.avi',
 'CR32a9735-CR32a9a70-000052.avi',
 'CR3dcab5a-CR3dcb7da-000039.avi',
 'CR32a96ab-CR4884efc-000046.avi',
 'CR32a96d7-CR32a9982-000064.avi',
 'CR32a756f-CR32a99d9-000048.avi',
 'CR3dca809-CR3dcb1ac-000036.avi',
 'CR3dcabd9-CR3dcadb6-000065.avi',
 'CR3dcab9b-CR3dcb494-000068.avi',
 'CR3dca6ee-CR3dcadf9-000044.avi',
 'CR32a95e5-CR3dcaeaf-000034.avi',
 'CR3dca6c5-CR3dcada7-000034.avi',
 'CR3dca779-CR3dca9d9-000034.avi',
 'CR32a7561-CR32a758f-000035.avi',
 'CR3dca6f0-CR3dcb3d1-000029.avi',
 'CR32a7556-CR32a9a75-000007.avi',
 'CR3dca71c-CR3dcb204-000030.avi',
 'CR3dcb080-CR3dcb1c9-000060.avi',
 'CR32a95cc-CR32a97f2-000048.avi',
 'CR32a96dd-CR3dcaa11-000049.avi',
 'CR32a95c6-CR3dcb294-000052.avi',
 'CR32a96d2-CR3dcaf71-000030.avi',
 'CR3dcab9e-CR3dcad24-000055.avi',
 'CR32a971d-CR32a9a25-000076.avi',
 'CR3dcabfb-CR3dcae0d-000044.avi',
 'CR32a756b-CR32a7599-000053.avi',
 'CR32a9662-CR3dcaaf6-000047.avi',
 'CR3dcab8b-CR3dcacfc-000043.avi',
 'CR32a9641-CR3dcb4a1-000048.avi',
 'CR3dcac90-CR3dcb37c-000047.avi',
 'CR32a96c0-CR32a9955-000062.avi',
 'CR3dcab8f-CR3dcad59-000053.avi',
 'CR3dcb531-CR3dcb79d-000067.avi',
 'CR3dca84c-CR3dcab3e-000092.avi',
 'CR3dcb0af-CR3dcb35c-000051.avi',
 'CR32a9650-CR3dcaf27-000053.avi',
 'CR3dcab73-CR3dcacce-000067.avi',
 'CR32a9617-CR3dcacd6-000046.avi',
 'CR32a7573-CR3dcad9e-000033.avi',
 'CR3dca7ab-CR3dcb88d-000027.avi',
 'CR3dca793-CR3dcb87c-000052.avi',
 'CR3dca723-CR3dcb790-000046.avi',
 'CR32a756f-CR32a98ff-000043.avi',
 'CR3dcabed-CR3dcb3fd-000032.avi',
 'CR3dcb142-CR3dcb3a7-000071.avi',
 'CR32a95c1-CR32a977d-000040.avi',
 'CR3dca83b-CR3dcb46b-000063.avi',
 'CR32a96d7-CR3dcb874-000032.avi',
 'CR3dcb07d-CR3dcb1c4-000097.avi',
 'CR32a9641-CR4884f4b-000052.avi',
 'CR32a9701-CR32a99e7-000030.avi',
 'CR3dcabf9-CR3dcb015-000035.avi',
 'CR32a9671-CR3dcaf65-000061.avi',
 'CR32a755a-CR32a97b1-000046.avi',
 'CR3dcabcc-CR3dcad95-000066.avi',
 'CR3dcb16d-CR3dcb427-000056.avi',
 'CR3dca6b3-CR3dca9b6-000046.avi',
 'CR3dcab9d-CR3dcb024-000031.avi',
 'CR32a96c4-CR3dca966-000048.avi',
 'CR3dcb08d-CR3dcb1e3-000045.avi',
 'CR3dcaba4-CR3dcad92-000056.avi',
 'CR3dca703-CR3dcadae-000042.avi',
 'CR32a9732-CR32a9a66-000048.avi',
 'CR32a95c6-CR32a98f5-000084.avi',
 'CR32a95e3-CR32a98b1-000061.avi',
 'CR3dcac94-CR3dcaf89-000030.avi',
 'CR3dcb0f5-CR3dcb2c6-000016.avi',
 'CR3dca753-CR3dca98c-000069.avi',
 'CR3dca73f-CR3dcb39e-000045.avi',
 'CR32a7563-CR32a97df-000065.avi',
 'CR32a975f-CR3dcb678-000063.avi',
 'CR3dca6f1-CR3dcb31a-000035.avi',
 'CR32a964b-CR4884eeb-000049.avi',
 'CR32a962d-CR3dcaef5-000037.avi',
 'CR32a9601-CR32a99c5-000049.avi',
 'CR3dcabac-CR3dcb36c-000064.avi',
 'CR32a9745-CR32a9a91-000056.avi',
 'CR32a9648-CR3dcaad4-000035.avi',
 'CR32a9711-CR3dcb8ba-000036.avi',
 'CR32a7580-CR32a97ed-000064.avi',
 'CR32a96c7-CR32a9961-000061.avi',
 'CR3dca7d1-CR3dcb986-000053.avi',
 'CR32a95ed-CR32a99e4-000095.avi',
 'CR3dcb542-CR3dcb758-000051.avi',
 'CR32a9748-CR3dcacbb-000034.avi',
 'CR32a967c-CR32a98c3-000098.avi',
 'CR3dca6da-CR3dca8d1-000085.avi',
 'CR32a9711-CR3dcb7a6-000058.avi',
 'CR3dcb187-CR3dcb480-000076.avi',
 'CR32a9730-CR3dcaf50-000040.avi',
 'CR3dcb180-CR3dcb45b-000066.avi',
 'CR32a95c5-CR32a988e-000048.avi',
 'CR3dca714-CR3dcb60b-000056.avi',
 'CR3dcb06e-CR3dcb65e-000051.avi',
 'CR32a9652-CR32a98d6-000029.avi',
 'CR3dcabc1-CR3dcb3b4-000088.avi',
 'CR32a7580-CR32a9a11-000047.avi',
 'CR3dca7c4-CR3dcaa4b-000022.avi',
 'CR3dcb555-CR3dcb7aa-000035.avi',
 'CR3dca743-CR3dca971-000070.avi',
 'CR32a9677-CR3dcadc3-000033.avi',
 'CR3dca7e1-CR3dcaa79-000032.avi',
 'CR32a96e8-CR3dcb8bd-000064.avi',
 'CR32a973e-CR3dcaa66-000036.avi',
 'CR32a95f5-CR4884ec3-000047.avi',
 'CR3dca719-CR3dcb02f-000081.avi',
 'CR3dcb0b5-CR3dcb8b6-000051.avi',
 'CR32a7572-CR3dca8b7-000057.avi',
 'CR32a9729-CR3dcb958-000050.avi',
 'CR3dca6b3-CR3dcb849-000035.avi',
 'CR3dcb10e-CR3dcb39b-000045.avi',
 'CR3dcab83-CR3dcb308-000064.avi',
 'CR3dca735-CR3dcae4d-000045.avi',
 'CR32a755c-CR3dcb018-000037.avi',
 'CR3dcac72-CR3dcaf24-000043.avi',
 'CR32a95cf-CR32a9952-000056.avi',
 'CR3dcb124-CR3dcb358-000051.avi',
 'CR32a9677-CR3dca91e-000064.avi',
 'CR3dca7a7-CR3dcb32d-000092.avi',
 'CR32a976d-CR32a9b00-000033.avi',
 'CR32a9723-CR3dcad65-000039.avi',
 'CR32a9623-CR3dcad78-000041.avi',
 'CR32a963a-CR3dcb7d2-000060.avi',
 'CR32a9634-CR32a982c-000028.avi',
 'CR3dca711-CR3dca92a-000036.avi',
 'CR3dca688-CR3dca85f-000038.avi',
 'CR32a95eb-CR3dcb80a-000051.avi',
 'CR4884ea9-CR4884f0f-000056.avi',
 'CR3dcb5b2-CR3dcb8be-000051.avi',
 'CR32a9626-CR3dcb906-000058.avi',
 'CR3dcb14a-CR4884ee6-000029.avi',
 'CR3dcb4ce-CR3dcb5f7-000064.avi',
 'CR3dcac2d-CR3dcae81-000030.avi',
 'CR3dca803-CR3dcaf09-000058.avi',
 'CR3dcb4e6-CR3dcb633-000064.avi',
 'CR3dcab5b-CR3dcaca6-000049.avi',
 'CR3dca685-CR3dcb5b9-000037.avi',
 'CR32a95eb-CR3dcb946-000067.avi',
 'CR3dca6ed-CR3dcb41e-000049.avi',
 'CR32a95fd-CR32a97c9-000058.avi',
 'CR32a963d-CR3dcaefb-000110.avi',
 'CR32a9662-CR3dcb947-000039.avi',
 'CR32a9739-CR32a9a76-000035.avi',
 'CR3dcab83-CR3dcacf1-000052.avi',
 'CR32a9673-CR32a9983-000049.avi',
 'CR3dcac1e-CR3dcae57-000051.avi',
 'CR3dcb0a1-CR3dcb216-000082.avi',
 'CR32a961d-CR32a9801-000044.avi',
 'CR32a972c-CR32a9a52-000040.avi',
 'CR3dcafb9-CR3dcb47b-000072.avi',
 'CR3dcb190-CR3dcb49c-000043.avi',
 'CR3dcb11a-CR3dcb337-000042.avi',
 'CR3dcabb2-CR3dcb71f-000034.avi',
 'CR3dca793-CR3dcaaec-000048.avi',
 'CR3dcb4bb-CR3dcb5c1-000061.avi',
 'CR32a756f-CR32a99fb-000019.avi',
 'CR3dca7da-CR3dcab35-000067.avi',
 'CR3dcb598-CR3dcb86d-000070.avi',
 'CR3dcb8d5-CR3dcb923-000057.avi',
 'CR32a756f-CR32a97d6-000012.avi',
 'CR32a9774-CR32a9b1a-000121.avi',
 'CR32a7555-CR32a9850-000040.avi',
 'CR3dcabb2-CR3dcb1ad-000042.avi',
 'CR32a7560-CR32a758d-000080.avi',
 'CR3dca738-CR3dca961-000082.avi',
 'CR32a962d-CR3dcad32-000035.avi',
 'CR32a962d-CR3dcb7f3-000055.avi',
 'CR3dcb18e-CR3dcb499-000041.avi',
 'CR3dcaba9-CR3dcada3-000061.avi',
 'CR3dcac2e-CR3dcae85-000038.avi',
 'CR32a7578-CR32a75a7-000034.avi',
 'CR32a96d5-CR32a997e-000084.avi',
 'CR3dcb151-CR3dcb3cc-000045.avi',
 'CR32a7562-CR32a9868-000054.avi',
 'CR3dcb0a7-CR3dcb793-000042.avi',
 'CR32a9688-CR3dcb603-000103.avi',
 'CR3dcac42-CR3dcaeb3-000049.avi',
 'CR32a9653-CR3dcb393-000054.avi',
 'CR3dca747-CR3dca9c5-000048.avi',
 'CR3dcb599-CR3dcb86f-000035.avi',
 'CR32a755b-CR32a9aa6-000036.avi',
 'CR32a9723-CR3dcb791-000054.avi',
 'CR32a9700-CR3dcb809-000052.avi',
 'CR32a7571-CR32a9970-000038.avi',
 'CR3dca842-CR3dcb7be-000050.avi',
 'CR3dcaf98-CR3dcb645-000039.avi',
 'CR3dcab5a-CR3dcb91f-000063.avi',
 'CR32a96ce-CR3dca97e-000078.avi',
 'CR3dcb12d-CR3dcb36f-000074.avi',
 'CR32a9724-CR3dcaaa5-000055.avi',
 'CR32a9624-CR32a9865-000082.avi',
 'CR3dca836-CR3dcaced-000035.avi',
 'CR3dcb0d6-CR3dcb77e-000039.avi',
 'CR3dca7f4-CR3dcaaa2-000071.avi',
 'CR3dcab66-CR3dcacb6-000071.avi',
 'CR32a973d-CR32a9a7e-000042.avi',
 'CR3dcb8ee-CR3dcb985-000050.avi',
 'CR32a962b-CR32a9819-000040.avi',
 'CR32a975f-CR32a9ad7-000067.avi',
 'CR3dcafc3-CR3dcb3ba-000054.avi',
 'CR32a9749-CR3dcaf37-000035.avi',
 'CR3dca814-CR3dcaad9-000145.avi',
 'CR3dcb0ae-CR3dcb701-000026.avi',
 'CR3dcb083-CR3dcb1cd-000047.avi',
 'CR3dcab61-CR3dcad88-000032.avi',
 'CR3dcaba2-CR3dcae7d-000078.avi',
 'CR3dcb149-CR3dcb40d-000084.avi',
 'CR3dca6b5-CR3dcb261-000047.avi',
 'CR3dcb197-CR3dcb4b3-000068.avi',
 'CR3dca7d3-CR3dcaa60-000073.avi',
 'CR3dca714-CR4884ef4-000043.avi',
 'CR3dca7d0-CR3dcaa5d-000044.avi',
 'CR3dca7ec-CR3dcaf3a-000036.avi',
 'CR32a961d-CR3dcb89f-000029.avi',
 'CR32a96a3-CR3dcaca4-000065.avi',
 'CR3dcb127-CR3dcb428-000060.avi',
 'CR3dcab72-CR3dcacc9-000055.avi',
 'CR3dcb092-CR3dcb1ef-000069.avi',
 'CR3dcb530-CR3dcb727-000041.avi',
 'CR3dcb086-CR3dcb1d4-000076.avi',
 'CR3dcb52a-CR3dcb703-000084.avi',
 'CR3dca718-CR3dcb83f-000027.avi',
 'CR3dcb085-CR3dcb481-000041.avi',
 'CR3dca702-CR3dca90d-000025.avi',
 'CR32a967a-CR32a98bf-000070.avi',
 'CR32a95ef-CR32a9824-000112.avi',
 'CR32a9749-CR32a9a9b-000070.avi',
 'CR32a95e0-CR32a979f-000083.avi',
 'CR3dca825-CR3dcaaf9-000031.avi',
 'CR3dca6be-CR3dcb6f4-000045.avi',
 'CR32a95be-CR32a9a31-000051.avi',
 'CR32a7570-CR32a97b4-000089.avi',
 'CR3dcb16a-CR3dcb806-000033.avi',
 'CR3dcac7a-CR3dcb392-000059.avi',
 'CR32a976f-CR3dcb755-000029.avi',
 'CR32a976f-CR3dcb73f-000040.avi',
 'CR32a96cc-CR4884ed2-000036.avi',
 'CR3dcb176-CR3dcb43e-000084.avi',
 'CR3dca747-CR3dcb30f-000047.avi',
 'CR32a964f-CR32a99cc-000045.avi',
 'CR3dcb08e-CR3dcb406-000047.avi',
 'CR32a9621-CR3dcb884-000043.avi',
 'CR3dca71b-CR3dca937-000038.avi',
 'CR32a9611-CR3dca8ff-000036.avi',
 'CR3dca733-CR3dca957-000076.avi',
 'CR3dca83d-CR3dcab25-000080.avi',
 'CR32a9685-CR32a9a03-000044.avi',
 'CR3dcb0b7-CR3dcb23b-000050.avi',
 'CR3dca6c5-CR3dcb3b3-000024.avi',
 'CR3dcb4d3-CR3dcb604-000059.avi',
 'CR3dcac5d-CR3dcaee9-000076.avi',
 'CR32a95f7-CR32a97c2-000032.avi',
 'CR3dca82d-CR3dcab05-000019.avi',
 'CR32a756a-CR3dcb251-000033.avi',
 'CR32a7571-CR32a99ca-000078.avi',
 'CR32a9648-CR3dca962-000033.avi',
 'CR32a9743-CR3dcb65a-000057.avi',
 'CR3dca83f-CR3dcb945-000061.avi',
 'CR3dcab61-CR3dcb29e-000050.avi',
 'CR32a7580-CR32a9a8c-000077.avi',
 'CR32a9657-CR32a98b3-000039.avi',
 'CR32a96d4-CR3dcb916-000052.avi',
 'CR3dca756-CR3dca990-000038.avi',
 'CR32a7574-CR32a9829-000050.avi',
 'CR3dcb097-CR3dcb1fd-000047.avi',
 'CR32a9697-CR3dcb7ff-000038.avi',
 'CR4884eae-CR4884f35-000033.avi',
 'CR3dca6cb-CR3dca8ba-000041.avi',
 'CR3dca852-CR3dcb992-000049.avi',
 'CR32a9685-CR32a98d5-000041.avi',
 'CR32a96c6-CR32a995e-000084.avi',
 'CR3dca71b-CR3dcb3fe-000046.avi',
 'CR32a96ce-CR3dca869-000035.avi',
 'CR3dca7bf-CR3dcaadc-000048.avi',
 'CR32a975d-CR32a9ad0-000125.avi',
 'CR32a961f-CR32a9804-000036.avi',
 'CR3dcb585-CR3dcb847-000044.avi',
 'CR3dcac38-CR3dcb8b5-000059.avi',
 'CR32a96e8-CR3dcb438-000026.avi',
 'CR3dcabc8-CR3dcb353-000042.avi',
 'CR32a964d-CR3dcaf84-000040.avi',
 'CR3dcab5e-CR3dcacad-000053.avi',
 'CR32a96f8-CR32a9af0-000051.avi',
 'CR3dca683-CR3dcb246-000050.avi',
 'CR32a96f4-CR3dcab2d-000055.avi',
 'CR32a9742-CR3dca9b3-000068.avi',
 'CR32a961f-CR3dcb2c1-000070.avi',
 'CR32a9634-CR3dcb066-000026.avi',
 'CR32a9682-CR32a990a-000047.avi',
 'CR3dcabb7-CR3dcb7ab-000060.avi',
 'CR3dcaf9d-CR3dcb416-000054.avi',
 'CR3dcb553-CR3dcb95d-000024.avi',
 'CR3dcb06d-CR3dcb412-000100.avi',
 'CR3dca747-CR3dcac9f-000040.avi',
 'CR32a95f1-CR3dcb60f-000047.avi',
 'CR3dcb181-CR3dcb7d7-000030.avi',
 'CR3dca70a-CR3dcb934-000040.avi',
 'CR32a974f-CR3dcaa06-000064.avi',
 'CR3dcac06-CR3dcae28-000034.avi',
 'CR32a9604-CR32a990b-000056.avi',
 'CR4884e99-CR4884ec4-000058.avi',
 'CR3dcb06d-CR3dcb1a0-000023.avi',
 'CR3dcb14e-CR3dcb3c4-000040.avi',
 'CR3dca82d-CR3dcb357-000047.avi',
 'CR3dcb4f1-CR3dcb822-000067.avi',
 'CR32a9619-CR32a9927-000037.avi',
 'CR3dcac40-CR3dcaead-000048.avi',
 'CR3dcb10b-CR3dcb2fc-000071.avi',
 'CR3dcb084-CR3dcb817-000053.avi',
 'CR32a963a-CR32a9991-000084.avi',
 'CR32a96ab-CR32a992e-000067.avi',
 'CR3dca7fb-CR3dcaab1-000059.avi',
 'CR3dcac6b-CR3dcaf12-000075.avi',
 'CR3dca680-CR3dca854-000065.avi',
 'CR3dcb4d9-CR3dcb616-000068.avi',
 'CR3dca737-CR3dcafe0-000034.avi',
 'CR3dca79b-CR3dcaf53-000031.avi',
 'CR3dca7ab-CR3dcb3d9-000058.avi',
 'CR4884e96-CR4884ebb-000069.avi',
 'CR3dcb53c-CR3dcb749-000088.avi',
 'CR32a7556-CR32a99fd-000048.avi',
 'CR3dcab5a-CR3dcb3b0-000032.avi',
 'CR32a9694-CR32a98f3-000044.avi',
 'CR3dcb0c9-CR3dcb26b-000064.avi',
 'CR3dcabb2-CR3dcb869-000036.avi',
 'CR32a9722-CR3dcb2cb-000042.avi',
 'CR32a7557-CR32a7584-000051.avi',
 'CR4884e9e-CR4884ed0-000087.avi',
 'CR32a95c3-CR3dcb963-000076.avi',
 'CR3dca7ed-CR3dcaa96-000062.avi',
 'CR32a95bf-CR3dcb9a2-000084.avi',
 'CR3dcb552-CR3dcb78b-000088.avi',
 'CR3dcac2a-CR3dcae7c-000069.avi',
 'CR3dca7af-CR3dcadb2-000047.avi',
 'CR3dcb0d8-CR3dcb95f-000046.avi',
 'CR32a755d-CR32a758a-000041.avi',
 'CR32a961d-CR4884eea-000031.avi',
 'CR3dca6e6-CR3dca8e4-000043.avi',
 'CR3dcabe7-CR3dcae3e-000059.avi',
 'CR32a7568-CR32a9ade-000037.avi',
 'CR3dcb111-CR3dcb310-000049.avi',
 'CR32a96b9-CR32a99bb-000007.avi',
 'CR32a95bc-CR32a98b2-000047.avi',
 'CR32a964f-CR32a9a27-000038.avi',
 'CR32a95cc-CR32a99f8-000050.avi',
 'CR32a96a7-CR3dcb8a8-000034.avi',
 'CR32a9758-CR32a9ac9-000073.avi',
 'CR32a969e-CR32a9907-000090.avi',
 'CR32a7566-CR32a7594-000067.avi',
 'CR32a95e2-CR32a97a3-000047.avi',
 'CR3dcabde-CR3dcb770-000060.avi',
 'CR3dca7bf-CR3dcaa41-000041.avi',
 'CR32a95d7-CR32a9aec-000064.avi',
 'CR3dcb06d-CR3dcb40b-000042.avi',
 'CR3dca6ab-CR3dcaaee-000041.avi',
 'CR32a975d-CR3dcb8c2-000051.avi',
 'CR3dcab8f-CR3dcad04-000045.avi',
 'CR32a756c-CR32a759a-000038.avi',
 'CR3dcabe2-CR3dcaff2-000045.avi',
 'CR3dcb586-CR3dcb84a-000042.avi',
 'CR3dcac18-CR3dcae47-000073.avi',
 'CR32a96a3-CR3dca96e-000071.avi',

In [16]:
df_train_used = df[df["FileName"].isin(train_files)]
df_val_used   = df[df["FileName"].isin(val_files)]
df_test_used  = df[df["FileName"].isin(test_files)]

In [17]:
assert df_train_used["Split"].isin(range(0, 8)).all()
assert (df_val_used["Split"] == 8).all()
assert (df_test_used["Split"] == 9).all()

In [18]:
def age_distribution(df_subset):
    return (
        df_subset
        .groupby("Age")
        .size()
        .reset_index(name="n_subjects")
        .rename(columns={"Age": "age"})
        .sort_values("age")
        .reset_index(drop=True)
    )

train_age_df = age_distribution(df_train_used)
val_age_df   = age_distribution(df_val_used)
test_age_df  = age_distribution(df_test_used)

In [19]:
test_age_df

    age  n_subjects
0     0          12
1     1          14
2     2          15
3     3          18
4     4          15
5     5           9
6     6          14
7     7          11
8     8          14
9     9          10
10   10          17
11   11          16
12   12          18
13   13          17
14   14          16
15   15          24
16   16          22
17   17          29
18   18          23

In [20]:
train_age_df.to_csv('train_distribution.csv', index=False)
val_age_df.to_csv('val_distribution.csv', index=False)
test_age_df.to_csv('test_distribution.csv', index=False)